export const authConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  REGISTER_EMAIL_REQUEST: "USERS_REGISTER_EMAIL_REQUEST",
  REGISTER_EMAIL_SUCCESS: "USERS_REGISTER_EMAIL_SUCCESS",
  REGISTER_EMAIL_FAILURE: "USERS_REGISTER_EMAIL_FAILURE",

  LOGIN_REQUEST: "AUTHENTICATION_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTHENTICATION_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTHENTICATION_LOGIN_FAILURE",

  LOGOUT: "AUTHENTICATION_LOGOUT",

  FORGOT_PASSWORD_REQUEST: "AUTHENTICATION_FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "AUTHENTICATION_FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "AUTHENTICATION_FORGOT_PASSWORD_FAILURE",
  FORGOT_PASSWORD_CLEAR: "AUTHENTICATION_FORGOT_PASSWORD_CLEAR",

  RESET_PASSWORD_REQUEST: "AUTHENTICATION_RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "AUTHENTICATION_RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "AUTHENTICATION_RESET_PASSWORD_FAILURE",

  RESEND_EMAIL_REQUEST: "RESEND_EMAIL_REQUEST",
  RESEND_EMAIL_SUCCESS: "RESEND_EMAIL_SUCCESS",
  RESEND_EMAIL_FAILURE: "RESEND_EMAIL_FAILURE",

  VERIFY_EMAIL_REQUEST: "VERIFY_EMAIL_REQUEST",
  VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
  VERIFY_EMAIL_FAILURE: "VERIFY_EMAIL_FAILURE",

  NOT_VERIFIED_YET: "NOT_VERIFIED_YET",
  CLOSE: "CLOSE",
  DEFAULT_REGISTER: "DEFAULT_REGISTER",
};
