export const usersConstants = {
    REQUEST_GET_USERS: 'REQUEST_GET_USERS',
    REQUEST_GET_USERS_FAILED: 'REQUEST_GET_USERS_FAILED',
    REQUEST_GET_USERS_SUCCESS: 'REQUEST_GET_USERS_SUCCESS',
    REQUEST_CREATE_USERS: 'REQUEST_CREATE_USERS',
    REQUEST_CREATE_USERS_FAILED: 'REQUEST_CREATE_USERS_FAILED',
    REQUEST_CREATE_USERS_SUCCESS: 'REQUEST_CREATE_USERS_SUCCESS',
    REQUEST_UPDATE_USERS: 'REQUEST_UPDATE_USERS',
    REQUEST_UPDATE_USERS_FAILED: 'REQUEST_UPDATE_USERS_FAILED',
    REQUEST_UPDATE_USERS_SUCCESS: 'REQUEST_UPDATE_USERS_SUCCESS',
    REQUEST_DELETE_USERS_SUCCESS: 'REQUEST_DELETE_USERS_SUCCESS',
    REQUEST_DELETE_USER_SUCCESS: 'REQUEST_DELETE_USER_SUCCESS',
};
